theme = "dracula"
icons = "awesome"

[[block]]
block = "focused_window"
[block.format]
full = " $title.str(max_w:20) |"
short = " $title.str(max_w:10) |"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = "%Y-%m-%d %R"
