theme = "catppuccin_mocha"

[editor]
cursorline = true
color-modes = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator", "version-control"]
right = ["diagnostics", "workspace-diagnostics", "register", "position", "file-encoding"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

# Remap keys to be closer to neovim

[keys.insert]
"C-c" = "normal-mode"
